version: '2'

services:
  confluence:
    user: root
    restart: always
    image: atlassian/confluence-server:6.14.0-alpine
    container_name: confluence
    hostname: confluence
    networks:
      - confluencenet
    volumes:
      - confluencedata:/var/atlassian/application-data/confluence
      - ./atlassian-agent.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-agent.jar
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'CONFLUENCE_PROXY_NAME='
      - 'CONFLUENCE_PROXY_PORT='
      - 'CONFLUENCE_PROXY_SCHEME='
      - 'CONFLUENCE_DELAYED_START='
      - JAVA_OPTS=-javaagent:/opt/atlassian/confluence/confluence/WEB-INF/lib/atlassian-agent.jar ${JAVA_OPTS}
    labels:
      com.blacklabelops.description: "Atlassian Confluence"
      com.blacklabelops.service: "confluence"
    depends_on:
      - postgresql

  postgresql:
    restart: always
    image: postgres:11.5
    container_name: postgres
    hostname: postgres
    networks:
      - confluencenet
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=confluencedb'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=changeme'
      - 'POSTGRES_DB=confluencedb'
      - 'POSTGRES_ENCODING=UTF8'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    labels:
      com.blacklabelops.description: "PostgreSQL Database Server"
      com.blacklabelops.service: "postgresql"

volumes:
  confluencedata:
    external: false
  postgresqldata:
    external: false

networks:
  confluencenet:
    driver: bridge
