apiVersion: v1
kind: PersistentVolume
metadata:
  name: xray-postgres-pv-NAMESPACE
spec:
  capacity:
    storage: 50Gi 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: POSTGRES_VOLUME_ID
