apiVersion: v1
kind: Template
metadata:
    name: xray-data-pvc-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "JFrog Xray Data PVC"
        description: |-
          This template creates a PVC to be used by JFrog Xray
        tags: "ci-cd"

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: xray-data-pvc
    namespace: ${NAMESPACE}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${XRAY_DATA_PVC_SIZE} 
    volumeName: xray-data-pv-${NAMESPACE}

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: XRAY_DATA_PVC_SIZE
    description: Size of JFrog Xray data
    displayName: Size of JFrog Xray data
    value: 100Gi
    required: true
