apiVersion: v1
kind: Template
metadata:
    name: artifactory-licenses-secret-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "Artifactory Licenses"
        description: |-
          This template creates a Secret to store Artifactory licenses to be
          used to by a Artifactory cluster.
        tags: "ci-cd"

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
        name: ${LICENSES_SECRET_NAME}
        namespace: ${NAMESPACE}
    data:
        artifactory.cluster.license: ${ARTIFACTORY_LICENSES_BASE_64}

parameters:
  - name: NAMESPACE
    description: Secret Namespace
    displayName: Namespace
    required: true
  - name: LICENSES_SECRET_NAME
    description: Artifactory licenses secret name
    displayName: Artifactory licenses secret name
    required: true
  - name: ARTIFACTORY_LICENSES_BASE_64
    description: Artifactory licenses in base 64
    displayName: Artifactory licences in base 64
    required: true
