apiVersion: v1
kind: Template
metadata:
    name: artifactory-master-key-secret-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "Artifactory Cluster Master Key"
        description: |-
          This template creates a Secret to store Artifactory cluster master key.
          This key should be used by the nodes to identify them as members of the
          same cluster.

          You can generate a new master key and convert it to base 64 using the
          following command:
              openssl rand -hex 16 | base64
        tags: "ci-cd"

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
        name: ${MASTER_KEY_SECRET_NAME}
        namespace: ${NAMESPACE}
    data:
        master.key: ${ARTIFACTORY_MASTER_KEY_BASE_64}

parameters:
  - name: NAMESPACE
    description: Secret Namespace
    displayName: Namespace
    required: true
  - name: MASTER_KEY_SECRET_NAME
    description: Artifactory Master Key secret name
    displayName: Artifactory Master Key secret name
    required: true
  - name: ARTIFACTORY_MASTER_KEY_BASE_64
    description: Artifactory Master Key in base 64
    displayName: Artifactory Master Key in base 64
    required: true
