concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gateway"
  url = "http://<gitlab IP address>/"
  clone_url = "http://<gitlab IP address>/"
  token = "<gitlab runner token>"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "python:3.7"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache","/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.custom]
    run_exec = ""