apiVersion: v1
kind: Template
metadata:
    name: artifactory-service-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "Artifactory Service"
        description: |-
          This template creates Services and Routes for an Artifactory cluster.
        tags: "ci-cd"

objects:

  - apiVersion: v1
    kind: Route
    metadata:
        name: ${NAME}
        namespace: ${NAMESPACE}
    spec:
        to:
            kind: Service
            name: ${NAME}
        port:
            targetPort: web
        tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect

  - apiVersion: v1
    kind: Route
    metadata:
        name: docker-virtual
        namespace: ${NAMESPACE}
    spec:
        to:
            kind: Service
            name: ${NAME}
        port:
            targetPort: web
        tls:
            termination: edge
            insecureEdgeTerminationPolicy: Redirect

  - apiVersion: v1
    kind: Service
    metadata:
        name: ${NAME}
        namespace: ${NAMESPACE}
    spec:
        ports:
          - name: web
            port: 8081
            protocol: TCP
            targetPort: 8081
        selector:
            artifactory-ha: ${NAME}

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: NAME
    description: Artifactory HA Name
    displayName: Artifactory HA Name
    required: true
