apiVersion: v1
kind: Template
metadata:
    name: postgresql-secret-template

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
        name: ${POSTGRESQL_SECRET_NAME}
        namespace: ${NAMESPACE}
    type: kubernetes.io/basic-auth
    data:
        username: ${POSTGRESQL_USERNAME}
        password: ${POSTGRESQL_PASSWORD}

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: POSTGRESQL_SECRET_NAME
    description: PostgreSQL secret name
    displayName: PostgreSQL secret name
    value: "postgresql-credentials"
  - name: POSTGRESQL_USERNAME
    description: PostgreSQL username
    displayName: PostgreSQL username
  - name: POSTGRESQL_PASSWORD
    description: PostgreSQL password
    displayName: PostgreSQL password
