apiVersion: v1
kind: Template
metadata:
    name: artifactory-data-pvc-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "Artifactory Data PVC"
        description: |-
          This template creates a PVC to be used by all the nodes in an
          Artifactory cluster using NFS to store artifacts data.
        tags: "ci-cd"

objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
        name: ${NAME}-data
        namespace: ${NAMESPACE}
    spec:
        resources:
            requests:
                storage: ${ARTIFACTORY_DATA_PVC_SIZE}
        accessModes:
          - "ReadWriteMany"

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: NAME
    description: Artifactory HA Name
    displayName: Artifactory HA Name
    required: true
  - name: ARTIFACTORY_DATA_PVC_SIZE
    description: Artifactory Data folder PVC size
    displayName: Artifactory Data folder PVC size
    value: "20Gi"
    required: true
