apiVersion: v1
kind: Template
metadata:
    name: xray-rabbitmq-configmap-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "RabbitMQ ConfigMap"
        description: |-
          This template creates a ConfigMap to be used by RabbitMQ
        tags: "ci-cd"

objects:
- apiVersion: v1
  data:
    rabbitmq.config: "[{rabbit,[{loopback_users, []},{vm_memory_high_watermark,
    {absolute, \"1GiB\"}}]}]."
  kind: ConfigMap
  metadata:
    name: xray-rabbitmq-conf
    namespace: ${NAMESPACE}

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
