apiVersion: v1
kind: PersistentVolume
metadata:
  name: xray-rabbitmq-pv-NAMESPACE
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/xraydb/rabbitmq
    server: NFS_SERVER 
  persistentVolumeReclaimPolicy: Retain
