apiVersion: v1
kind: PersistentVolume
metadata:
  name: xray-rabbitmq-pv-NAMESPACE
spec:
  capacity:
    storage: 50Gi 
  accessModes:
    - "ReadWriteOnce"
  awsElasticBlockStore:
    fsType: "ext4"
    volumeID: RABBITMQ_VOLUME_ID
