port: 3000
bindIP: 0.0.0.0
db:
  type: $(DB_TYPE)
  host: $(DB_HOST)
  port: $(DB_PORT)
  user: $(DB_USER)
  pass: $(DB_PASS)
  db: $(DB_NAME)
  storage: $(DB_FILEPATH)
  ssl: $(DB_SSL)
trustProxy: $(TRUST_PROXY)
logLevel: info

lang: fa

# Enable for right to left languages (e.g. arabic):
langRtl: true