apiVersion: v1
kind: PersistentVolume
metadata:
  name: xray-mongodb-pv-NAMESPACE
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  nfs:
    path: /data/xraydb/mongodb
    server: NFS_SERVER 
  persistentVolumeReclaimPolicy: Retain
