apiVersion: v1
kind: Template
metadata:
    name: xray-mongodb-configmap-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "MongoDB ConfigMap"
        description: |-
          This template creates a ConfigMap to be used to bootstrap MongoDB
        tags: "ci-cd"

objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: xray-mongodb-setup
    namespace: ${NAMESPACE}
  data:
    createMongoDBUsers.js: |
      //JFrog Xray MongoDB Bootstrap
      //Creating default admin user
      var adminUser = {
        user:"admin",
        pwd: "password",
        roles: ["root"],
        customData: {
            createdBy: "JFrog Xray installer"
        }
      }
      db.getSiblingDB("admin").createUser(adminUser)
      //Creating default xray user
      var xrayUser = {
        user:"xray",
        pwd: "password",
        roles: ["dbOwner"],
        customData: {
            createdBy: "JFrog Xray installer"
        }
      }
      //Authenticating as admin to create xray user
      var loginOutput = db.getSiblingDB("admin").auth(adminUser.user,adminUser.pwd)
      db.getSiblingDB("xray").createUser(xrayUser)
    setup.sh: |
      #!/bin/bash
        # Setup script to create MongoDB users
        MONGO_DATA=/data
        DB_CREATED_FLAG=${MONGO_DATA}/db/createMongoDBUsers.done
        errorExit () {
          echo; echo "ERROR: $1"; echo; exit 1
        }
        if [ ! -f ${DB_CREATED_FLAG} ]; then
          echo "Waiting for mongodb to come up"
          until mongo --eval "db.adminCommand('ping')" --host ${MONGODB_SERVICE_HOST} > /dev/null 2>&1; do
            echo "Waiting for db availability"
            sleep 2
          done
          echo "DB ready. Configuring..."
          mongo --host ${MONGODB_SERVICE_HOST} < /scripts/createMongoDBUsers.js || errorExit "DB user setup failed"
          touch ${DB_CREATED_FLAG} || errorExit "Creating ${DB_CREATED_FLAG} failed"
          echo "DB config done"
        else
          echo "${DB_CREATED_FLAG} exists! DB was already setup before. Skipping DB configuration..."
        fi
  
parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
