apiVersion: v1
kind: Template
metadata:
    name: postgresql-template

objects:

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
        name: ${NAME}
        namespace: ${NAMESPACE}
    spec:
        replicas: 1
        strategy:
            type: Recreate
        template:
            metadata:
                labels:
                    name: ${NAME}
            spec:
                serviceAccountName: ${SERVICE_ACCOUNT}

                initContainers:
                  - name: init-postgresql
                    image: ${INIT_CONTAINER_IMAGE}
                    command: ["sh", "-c", "chown -R 26:26 /var/lib/pgsql/data && rm -rf /var/lib/pgsql/data/lost+found"]
                    volumeMounts:
                      - name: ${NAME}-data
                        mountPath: /var/lib/pgsql/data

                containers:
                  - image: ''
                    imagePullPolicy: Always
                    name: ${NAME}
                    ports:
                      - containerPort: 5432
                        protocol: TCP
                    volumeMounts:
                      - name: ${NAME}-data
                        mountPath: /var/lib/pgsql/data
                    env:
                      - name: POSTGRESQL_USER
                        valueFrom:
                            secretKeyRef:
                                name: ${POSTGRESQL_SECRET_NAME}
                                key: username
                      - name: POSTGRESQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: ${POSTGRESQL_SECRET_NAME}
                                key: password
                      - name: POSTGRESQL_DATABASE
                        value: ${POSTGRESQL_DATABASE}

                volumes:
                  - name: ${NAME}-data
                    persistentVolumeClaim:
                        claimName: ${POSTGRESQL_PVC_NAME}
        triggers:
          - type: ImageChange
            imageChangeParams:
                automatic: true
                containerNames:
                  - ${NAME}
                from:
                    kind: ImageStreamTag
                    name: postgresql:${POSTGRESQL_VERSION}
                    namespace: openshift
          - type: ConfigChange
parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: NAME
    description: Service name
    displayName: Service name
    value: "postgresql"
  - name: SERVICE_ACCOUNT
    description: Service account
    displayName: Service account
    required: true
  - name: "POSTGRESQL_VERSION"
    description: PostgreSQL version
    displayName: PostgreSQL version
    value: "9.5"
  - name: POSTGRESQL_SECRET_NAME
    description: PostgreSQL secret name
    displayName: PostgreSQL secret name
    value: "postgresql-credentials"
  - name: "POSTGRESQL_DATABASE"
    description: PostgreSQL database name
    displayName: PostgreSQL database name
    value: "artifactory"
  - name: "POSTGRESQL_PVC_NAME"
    description: PostgreSQL PVC name
    displayName: PostgreSQL PVC name
    value: "postgresql"
  - name: INIT_CONTAINER_IMAGE
    description: Init container image
    displayName: Init container image
    value: "alpine:3.6"
    required: true
