apiVersion: v1
kind: Template
metadata:
    name: postgresql-volumes-claim-template

objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
        name: ${POSTGRESQL_PVC_NAME}
        namespace: ${NAMESPACE}
    spec:
        resources:
            requests:
                storage: ${POSTGRESQL_PVC_SIZE}
        accessModes:
          - "ReadWriteOnce"

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: POSTGRESQL_PVC_NAME
    description: PostgreSQL PVC name
    displayName: PostgreSQL PVC name
    value: "postgresql"
  - name: POSTGRESQL_PVC_SIZE
    description: PostgreSQL size
    displayName: PostgreSQL size
    value: "10Gi"
