version: '3'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.11.1
    container_name: artifactory
    ports:
     - 80:8081
    volumes:
     - /data/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
