kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-node1-claim
  labels:
    group: artifactory-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-node2-claim
  labels:
    group: artifactory-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
