kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
  labels:
    group: artifactory-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
