apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-service
  labels:
    app: nginx-k8s-service
    group: artifactory-k8s-demo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: port-1
    protocol: TCP
    targetPort: 80
  - port: 443
    name: port-2
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx-k8s-deployment
