
apiVersion: v1
kind: Template
metadata:
    name: artifactory-binarystore-nfs-config-map-template
    annotations:
        openshift.io/provider-display-name: "JFrog"
        openshift.io/display-name: "Artifactory NFS Binarystore"
        description: |-
          This template creates a ConfigMap to store the binarystore.xml file.
          The file content is suitable to Artifactory clusters using NFS.
        tags: "ci-cd"

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
        name: ${BINARYSTORE_CONFIG_MAP_NAME}
        namespace: ${NAMESPACE}
    data:
        binarystore.xml: |-
            <config version="v1">
                <chain>
                    <provider id="file-system" type="file-system">
                        <baseDataDir>${HA_DATA_DIR}</baseDataDir>
                    </provider>
                </chain>
            </config>

parameters:
  - name: NAMESPACE
    description: Namespace
    displayName: Namespace
    required: true
  - name: BINARYSTORE_CONFIG_MAP_NAME
    description: Artifactory Binarystore Config Map name
    displayName: Artifactory Binarystore Config Map name
    required: true
  - name: HA_DATA_DIR
    description: Shared Data Directory
    displayName: Shared Data Directory
    value: "/var/opt/jfrog/artifactory/data"
    required: true
