version: '3.7'

services:
  minio:
    hostname: minio
    image: minio/minio
    command: server --console-address ":9001" /data
    volumes:
      - ./data1:/data1
      - ./data2:/data2
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

