version: '3.7'
services:
  vpn:
    image: fcojean/l2tp-L2TP VPN Server-server
    restart: always
    env_file:
      - ./vpn.env
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    volumes:
      - /lib/modules:/lib/modules:ro
    privileged: true
    hostname: l2tp-L2TP VPN Server-server
    container_name: l2tp-L2TP VPN Server-server2
